---
title: "Home"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: true
editor_options:
  chunk_output_type: console
---

# Model
  * [Polygenic model](polygenic_model.html)
  * [Sparse model](sparse_model.html)
  * [mr.ash model](mrash_model.html)
  
# Data

## Expression data
  * [Fusion/TWAS gene expression models](fusion_expr.html)

# Simulations

## Proof of concept
  * [Proof of concept for this project using a single gene's data](simulation-singleG.html)

## Test polygenic model
Using WTCCC data

  * [Test polygenic model 1](simulation-WTCCC.html)
  
  * [Test polygenic model 2: use imputed expression](simulation-WTCCC2.html)

## Test mr.ash
Using UKbiobank data (chr22)

  * [Test mr.ash performance: only SNP effect](simulation-mr.ash-ukbchr22.html)

  
## Test mr.ash2s
A simplified version (mr.ash2) of `Veb_boost`: interative update of two mr.ash components

  * [Using some simple data](simulation_simpleveb-boost.html)
  
  * [Using UKbiobank data (chr22)](https://users.rcc.uchicago.edu/~simingz/simulation-simpleveb-boost-ukbchr22.html)
  
  
A simplified version (mr.ash2s): interative update of two mr.ash components, now including updates of sigma2 in each iteration and initiate with mr.ash for all.

  * [Using some simple data](simulation_simpleveb-boost2.html)
  
  * [Using UKbiobank data (chr22), fusion weights YFS ](https://users.rcc.uchicago.edu/~simingz/simulation-simpleveb-boost2-ukbchr22.html)
  
  * [Using UKbiobank data (chr22), fusion weights Adipose subcutaneous](https://users.rcc.uchicago.edu/~simingz/simulation-mr.ash2s-ukbchr22-gtex.adipose.html)
  
  * [Using UKbiobank data (chr22), weights of H3K27 from Xiaotong](https://users.rcc.uchicago.edu/~simingz/simulation-mr.ash2s-ukbchr22-H3K27.html)
  
## Test SUSIE for fine-mapping
  
  * [Using UKbiobank data (chr22), fusion weights YFS,  SUSIE `L=1`](simulation-susie-ukbchr22.html)
  * [Using UKbiobank data (chr22), fusion weights YFS, SUSIE `L=2`](simulation-susie-ukbchr22-L=2.html)
  * [Using UKbiobank data (chr22), fusion weights YFS,  SUSIE `L=3`](simulation-susie-ukbchr22-L=3.html)
  
  * [Using UKbiobank data (chr22), fusion weights Adipose, `L=1`](simulation-susie-ukbchr22-gtex.adipose.html)
  * [Using UKbiobank data (chr22), fusion weights Adipose, `L=2`](simulation-susie-ukbchr22-gtex.adipose-L=2.html)
  * [Using UKbiobank data (chr22), fusion weights Adipose, `L=3`](simulation-susie-ukbchr22-gtex.adipose-L=3.html)
  
## Summarize cTWAS results
We compare cTWAS results with other methods, summarizing results over multiple simulation runs.

  * [Using UKbiobank data (chr22), fusion weights Adipose](simulation-multi-ukbchr22-gtex.adipose.html)
  * [Using UKbiobank data (chr22), fusion weights Adipose, setting 2](simulation-multi-ukbchr22-gtex.adipose2.html)
  * [Using UKbiobank data (chr17:22), fusion weights Adipose](simulation-multi-ukbchr17to22-gtex.adipose.html) 
  * [Using UKbiobank data (chr17:22), fusion weights Adipose, using smaller sa2 grid in mr.ash](simulation-multi-ukbchr17to22-gtex.adipose_sa2_v2.html)
      *   [Visualization](https://users.rcc.uchicago.edu/~simingz/simulation-mr.ash2s-ukbchr17to22-gtex.adipose.html)
 
## mr.ash + SUSIE iterative
*  [Using UKbiobank data (chr17:22), fusion weights Adipose](simulation-susieI-ukbchr17to22-gtex.adipose.html) 
  *  [Using UKbiobank data (chr17:22), fusion weights Adipose, test prior's effect for susie](simulation-multi-ukbchr17to22-gtex.adipose_susieprior.html)
  
* [Using UKbiobank data (whole genome), fusion weights Adipose](simulation-susieI-ukbWG-gtex.adipose_s40.22.html) 
  * [Visualization](https://users.rcc.uchicago.edu/~simingz/simulation-susieI-ukbWG-gtex.adipose_visual.html)

# Related software
  * VEB-boost
    * [Problem description](VEB-boost-fitting.html)
    * Andrew's [software](https://github.com/stephenslab/VEB.Boost) and [workflowr website](https://andrewg3311.github.io/VEB-Boost-workflowR/VEB_Boost_Derivation.html)
    
  * mr.ash
    * [mr.ash](https://github.com/stephenslab/mr.ash.alpha) package
    * [mr.ash workflowr website](https://stephenslab.github.io/mr-ash-workflow/)

