---
title: "Simple simulations for a simplified version of web-boost-2"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(susieR)
```

## Simulation of data

20 blocks:

* Each block has either gene or SNP effect
* Each block has 99 SNPs and 1 gene. Each gene is linear sum of the previous 3 SNPs. 
* Each block, either the gene or the last eQTL has non-zero effect on trait

The first 4 blocks have gene effect.

```{r generate data}
set.seed(1)
N <- 4000
nblocks <- 20
block.size <- 100
p <- nblocks * block.size
n.eQTL <- 3  # number of eQTLs per gene
sigma.eQTL <- 0.5 # eQTL effect size
sigma.SNP <- 0.1 # effect size of causal SNP on trait
sigma.gene <- 0.1 # effect size of causal gene on trait
X <- matrix(rep(0,0), nrow=N, ncol=0)
gamma.gene <- rep(0, nblocks) # indicator of genes
gamma.gene[1:4] <- 1 
beta <- numeric(0)
SNP.idx <- numeric(0)
for (i in 1:nblocks) {
  # sample SNP data
  X.block.SNP <- matrix(rnorm(N*(block.size-1)), nrow=N, ncol=block.size-1)
  SNP.idx <- c(SNP.idx, 1:(block.size-1) + (i-1)*block.size)
  
  # generate gene data: use the previous few SNPs as eQTL
  effects.eQTL <- rnorm(n.eQTL, 0, sigma.eQTL)
  X.block.gene <- X.block.SNP[, (block.size - n.eQTL):(block.size - 1)] %*% effects.eQTL
  X.block = cbind(X.block.SNP, X.block.gene)
  X <- cbind(X, X.block)
  
  # sample beta
  if (gamma.gene[i] == 1) { # gene effect in this block
    beta.SNP <- rep(0, block.size - 1)
    beta.gene <- rnorm(1, 0, sigma.gene)
  } else { # SNP effect in this block
    beta.SNP <- c(rep(0, block.size - 2), rnorm(1, 0, sigma.SNP))
    beta.gene <- 0
  }
  beta.block <- c(beta.SNP, beta.gene)
  beta <- c(beta, beta.block)
}
sigma.e <- 1
y <- X %*% beta + rnorm(N, 0, sigma.e)
gene.idx <- (1:nblocks) * block.size
```


```{r plot functions}
plot_pip <- function(indi, pip, pipcut = 0.1) {
  x <- barplot(indi, main = "PIP")
  points(x, pip, pch=19, col="red")
  pred <- which(pip > pipcut)
  real <- which(indi==1)
  tp <- length(intersect(pred, real))/length(pred)
  fp <- 1 - tp
  fn <- length(setdiff(real, pred))/length(real)
  cat("false positive rate: ", fp, "\n")
  cat("false negative rate: ", fn, "\n")
}

```

## Run susie

Fix prior as given, using truth.

```{r run susie, gene}
p.snp <- length(SNP.idx)
p.gene <- length(gene.idx)

prior.SNP <- 16/2000
prior.gene <- 4/20
indi.gene <- c(rep(1,4), rep(0,16))

prior <- rep(0, dim(X)[2])
prior[gene.idx] <- prior.gene
prior[SNP.idx] <- prior.SNP

res <- susie(X,y,L=1, prior_weights=prior)

print("for gene effect: ")
plot_pip(indi.gene, res$pip[gene.idx])
```
