---
title: "Test mr.ash performance"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r plot functions}
library(mr.ash.alpha)
source("~/causalTWAS/causal-TWAS/code/fit_mr.ash.R")

summary_mr.ash <- function(fit){
  cat("pi1 = ", 1-fit$pi[[1]], "\n")
  pve <- get_pve(fit)
  cat("pve : ", pve, "\n")
}

plot_beta <- function(beta,beta.pm, ...){
  plot( beta, pch=19, col ="darkgreen", ...)
  points(beta.pm, pch =19, col = "red")
  legend("topright", legend=c("true beta", "posterior mean"),
       col=c("darkgreen", "red"), pch=19)
}
```

```{r output dir}
outputdir <- "~/causalTWAS/simulations/simulation_ashtest_20200429/"
```

## Simulation 1
True parameters:
```{r para 1}
readLines(paste0(outputdir, "param-20200429-1.R"))
```


ASH results:

```{r sim 1}
load(paste0(outputdir, "mr.ash_20200429-1-mr.ash-res.Rd"))
summary_mr.ash(mr.ash.fit)
```

## Simulation 2

True parameters:
```{r para 2}
readLines(paste0(outputdir, "param-20200429-2.R"))
```

ASH results:

```{r sim 2}
load(paste0(outputdir, "mr.ash_20200429-2-mr.ash-res.Rd"))
summary_mr.ash(mr.ash.fit)
```

## Simulation 3

True parameters:
```{r para 3}
readLines(paste0(outputdir, "param-20200429-3.R"))
```

ASH results:

```{r sim 3}
load(paste0(outputdir, "mr.ash_20200429-3-mr.ash-res.Rd"))
summary_mr.ash(mr.ash.fit)
```

## Simulation 4

True parameters:
```{r para 4}
readLines(paste0(outputdir, "param-20200429-4.R"))
```

ASH results:

```{r sim 4}
load(paste0(outputdir, "mr.ash_20200429-4-mr.ash-res.Rd"))
summary_mr.ash(mr.ash.fit)
```
