---
title: "Test SUSIE (L=3) for regions near genes (500kb flanking)"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(eval=T, warning = F)
```

```{r plot functions, eval=T}
library(mr.ash.alpha)
library(data.table)
suppressMessages({library(plotly)})

plot_pip <- function(dt){
  pal <- c("salmon", "darkgreen")
  pal <- setNames(pal, c("Causal", "Non causal"))
  
  fig <- plot_ly(dt, x = ~ pos, y = ~ pip, type = 'scatter', mode = 'markers', color = ~ ifcausal, colors = pal, text = ~paste("Name: ", name), width = 600, height = 400)

  fig <- fig %>% layout( yaxis = list(title = "PIP"), plot_bgcolor='#ebf6fc')
  return(fig)
}

plot_all <- function(susieres, mrashres.gene, mrashres.snp, title){
  dt <- read.table(susieres , header =T)
  
  a <- read.table(mrashres.gene , header =T)
  a[a$ifcausal == 1, "ifcausal"] = "Causal"
  a[a$ifcausal == 0, "ifcausal"] = "Non causal"
  
  dt.gene <- merge(dt, a, by= "name")

  a <- read.table(mrashres.snp , header =T)
  a[a$ifcausal == 1, "ifcausal"] = "Causal"
  a[a$ifcausal == 0, "ifcausal"] = "Non causal"
  
  dt.snp <- merge(dt, a, by= "name")
  
  fig1 <- plot_pip(dt.gene)
  fig2 <- plot_pip(dt.snp)

  fig <- subplot(fig1, fig2, nrows= 2, shareX = T, titleY = T)
  
  fig <- fig %>% layout(title = title, autosize = F,  margin = 0.02,
    xaxis = list(title = "Genomic position"))
  
  fig <- fig %>% toWebGL()
  fig
}
```


```{r output dir, eval=T}
simdatadir <- "~/causalTWAS/simulations/simulation_ashtest_20200503/"
outputdir <- "~/causalTWAS/simulations/simulation_susietest_20200604/"
mr.ash2dir <-  "~/causalTWAS/simulations/simulation_ashtest_20200527/"
```

## Simulation 1
```{r sim 1 setup, eval = T}
mrashtag <- "20200527-1"
susietag <- "20200604-1"
mrashres.gene <- paste0(mr.ash2dir, mrashtag, "-mr.ash2s.expr-res.expr.txt")
mrashres.snp <- paste0(mr.ash2dir, mrashtag, "-mr.ash2s.expr-res.snp.txt")
```

### FALSE positives in mr.ash2

```{r sim 1 3, out.width = "98%", out.height="95%", eval =T}
name <- "DGCR14"
susieres <- paste0(outputdir, susietag, ".L3-", name, "-susieres.txt")
plot_all(susieres, mrashres.gene, mrashres.snp, name)
```

```{r sim 1 4, out.width = "98%", out.height="95%"}
name <- "VPREB3"
susieres <- paste0(outputdir, susietag,".L3-", name, "-susieres.txt")
plot_all(susieres, mrashres.gene, mrashres.snp, name)
```

```{r sim 1 5, out.width = "98%", out.height="95%"}
name <- "TCN2"
susieres <- paste0(outputdir, susietag,".L3-", name, "-susieres.txt")
plot_all(susieres, mrashres.gene, mrashres.snp, name)
```


### FALSE negatives in mr.ash2
```{r sim 1 6, out.width = "98%", out.height="95%"}
name <- "CBX6"
susieres <- paste0(outputdir, susietag,".L3-", name, "-susieres.txt")
plot_all(susieres, mrashres.gene, mrashres.snp, name)
```

```{r sim 1 7, out.width = "98%", out.height="95%"}
name <- "CHEK2"
susieres <- paste0(outputdir, susietag,".L3-", name, "-susieres.txt")
plot_all(susieres, mrashres.gene, mrashres.snp, name)
```


## Simulation 3
Priors:
```{r para 3}
readLines(paste0(outputdir, "prior-3.R"))
```

SUSIE results:
```{r sim 3 setup}
mrashtag <- "20200527-3"
susietag <- "20200604-3"
mrashres.gene <- paste0(mr.ash2dir, mrashtag, "-mr.ash2s.expr-res.expr.txt")
mrashres.snp <- paste0(mr.ash2dir, mrashtag, "-mr.ash2s.expr-res.snp.txt")
```
```{r sim 3 1, out.width = "98%", out.height="95%"}

name <- "MCM5"
susieres <- paste0(outputdir, susietag,".L3-", name, "-susieres.txt")
plot_all(susieres, mrashres.gene, mrashres.snp, name)
```

```{r sim 3 2, out.width = "98%", out.height="95%"}
name <- "CBX6"
susieres <- paste0(outputdir, susietag,".L3-", name, "-susieres.txt")
plot_all(susieres, mrashres.gene, mrashres.snp, name)
```

[Zoomlocus view for this region](https://users.rcc.uchicago.edu/~simingz/chr22_39026778-40048655.pdf)
```{r zoomlocus, out.width = "85%", include = F}
file.copy("/home/simingz/causalTWAS/simulations/simulation_ashtest_20200503/snp_200622_CBX7/chr22_39026778-40048655.pdf", "~/public_html/chr22_39026778-40048655.pdf")
```

## Simulation 5

```{r sim 5 setup}
tag <- "20200527-5"
tag2 <- "expr-res"
susietag <- "20200527-5"
mrashres.gene <- paste0(mr.ash2dir, tag, "-mr.ash2s.", tag2, ".expr.txt")
mrashres.snp <- paste0(mr.ash2dir, tag, "-mr.ash2s.", tag2, ".snp.txt")
```

```{r sim 5 1, out.width = "98%", out.height="95%"}
name <- "CRELD2"
susieres <- paste0(outputdir, tag, ".", tag2, ".L3-", name, "-susieres.txt")
plot_all(susieres, mrashres.gene, mrashres.snp, name)
```
